# Use the official Nginx image as the base
FROM nginx

# Copy your Angular build output to the Nginx html folder
COPY ./dist/frontend/browser/ /usr/share/nginx/html/

COPY nginx-conf/test/default.test.conf /etc/nginx/conf.d/default.conf

# Start Nginx in the foreground (necessary for Docker to keep the container running)
CMD ["nginx", "-g", "daemon off;"]