create sequence announcement_sequence start with 1 increment by 1;
create sequence announcement_target_sequence start with 1 increment by 1;
create sequence assignments_sequence start with 1 increment by 1;
create sequence attendance_sequence start with 1 increment by 1;
create sequence class_schedule_sequence start with 1 increment by 1;
create sequence class_sequence start with 1 increment by 1;
create sequence grade_class_assignment_sequence start with 1 increment by 1;
create sequence main_topic_sequence start with 1 increment by 1;
create sequence semester_sequence start with 1 increment by 1;
create sequence sessions_sequence start with 1 increment by 1;
create sequence staff_perm_sequence start with 1 increment by 1;
create sequence staff_sequence start with 1 increment by 1;
create sequence student_enrollments_sequence start with 1 increment by 1;
create sequence student_sequence start with 1 increment by 1;
create sequence students_assignments_sequence start with 1 increment by 1;
create sequence sub_topic_sequence start with 1 increment by 1;
create table announcement_targets (announcement_id integer, class_id integer, id integer not null, primary key (id));
create table announcements (assignment_id integer, id integer not null, is_cancelled boolean, is_general boolean, semester_id integer, created_at timestamp(6), end_date_time timestamp(6), start_date_time timestamp(6), announcement_type varchar(255) check (announcement_type in ('INFO','ALERT','EVENT','REMINDER')), content TEXT, primary key (id));
create table assignments (class_id integer, id integer not null, total_grade integer, end_date_time timestamp(6), start_date_time timestamp(6), name varchar(255), primary key (id));
create table attendance (id integer not null, is_present boolean, session_id integer, student_id integer, primary key (id));
create table class_schedule (class_id integer, end_time time(6), id integer not null, start_time time(6), day_of_week varchar(255) check (day_of_week in ('SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY')), primary key (id));
create table classes (id integer not null, semester_id integer, staff_id integer, name varchar(255), primary key (id));
create table grade_class_assignment (class_id integer, id integer not null, semester_id integer, grade varchar(255) check (grade in ('FIRST','SECOND','THIRD','FOURTH','FIFTH','SIXTH','SEVENTH','EIGHTH','NINTH','TENTH','ELEVENTH','TWELFTH')), primary key (id));
create table main_topics (id integer not null, name varchar(255), primary key (id));
create table semesters (active boolean, default_classes boolean, end_date date, id integer not null, start_date date, name varchar(255), semester varchar(255) check (semester in ('FIRST','SECOND','SUMMER')), primary key (id));
create table session_topics (session_id integer not null, sub_topic_id integer not null);
create table sessions (cancelled boolean, class_id integer, date date, id integer not null, semester_id integer, staff_id integer, primary key (id));
create table staff (id integer not null, is_archived boolean, email varchar(255) unique, hash varchar(255), name varchar(255), primary key (id));
create table staff_permission (id integer not null, staff_id integer, permission varchar(255) check (permission in ('ADMIN','SUPERVISOR','INSTRUCTOR')), primary key (id));
create table student_class (class_id integer not null, student_id integer not null);
create table student_enrollments (enrollment_date date, id integer not null, semester_id integer, student_id integer, primary key (id));
create table students (date_of_birth date, id integer not null, area varchar(255), cpr varchar(255), email varchar(255), hash varchar(255), name varchar(255), telephone varchar(255), primary key (id));
create table students_assignments (assignment_done boolean, assignment_id integer, grade integer, id integer not null, student_id integer, submission_date timestamp(6), primary key (id));
create table sub_topics (id integer not null, main_topic_id integer, name varchar(255), primary key (id));
alter table if exists announcement_targets add constraint FK6i2lcfqud13ksff1q1qxt7vn2 foreign key (announcement_id) references announcements;
alter table if exists announcement_targets add constraint FKb7ayeilx8mxyrlvpbqed8wimg foreign key (class_id) references classes;
alter table if exists announcements add constraint FK4b5exklv8ntibnsj7gmwmscbw foreign key (assignment_id) references assignments;
alter table if exists announcements add constraint FKne5u9myxfui57llpimptdp1ug foreign key (semester_id) references semesters;
alter table if exists assignments add constraint FK15vvra255mh2h6merxffxmb2t foreign key (class_id) references classes;
alter table if exists attendance add constraint FKdqpwjnhfisqnxn9vrmunyaktb foreign key (session_id) references sessions;
alter table if exists attendance add constraint FK7121lveuhtmu9wa6m90ayd5yg foreign key (student_id) references students;
alter table if exists class_schedule add constraint FK9fplehvxxgfj35vacj8b0qabh foreign key (class_id) references classes;
alter table if exists classes add constraint FK8menn4iwjhqtjd5gq4bklkrj5 foreign key (semester_id) references semesters;
alter table if exists classes add constraint FK598kjxsn1wqp4xxehg4tiiff4 foreign key (staff_id) references staff;
alter table if exists grade_class_assignment add constraint FKc82ebbdjxj4dpqwijfd05mj62 foreign key (class_id) references classes;
alter table if exists grade_class_assignment add constraint FKqst0ta9duqv47130iy525wxxl foreign key (semester_id) references semesters;
alter table if exists session_topics add constraint FK6xbo46qb3fd3boyqrad7iohio foreign key (sub_topic_id) references sub_topics;
alter table if exists session_topics add constraint FKiyfw3lx03vqpl0pg6cr1rg531 foreign key (session_id) references sessions;
alter table if exists sessions add constraint FK2i1dhp8s39i3cjysgij9ieqit foreign key (semester_id) references semesters;
alter table if exists sessions add constraint FK4vg18mvn9bmhvgbhb0h157f69 foreign key (class_id) references classes;
alter table if exists sessions add constraint FK7923rii19ln8mplgx481smb3l foreign key (staff_id) references staff;
alter table if exists staff_permission add constraint FKe84oc7d8ga1qis2u2fivsctju foreign key (staff_id) references staff;
alter table if exists student_class add constraint FKntiefnoyunf7v0lu1lonoyr03 foreign key (class_id) references classes;
alter table if exists student_class add constraint FKcpdhpbj2fy2fqkanscji91frp foreign key (student_id) references students;
alter table if exists student_enrollments add constraint FK1ku95duukjw3bp1ub7i37lmss foreign key (semester_id) references semesters;
alter table if exists student_enrollments add constraint FKrvjgsoflhwarcj78oa1ltsr6k foreign key (student_id) references students;
alter table if exists students_assignments add constraint FKj5wx7vql50fyecedb0n1xeb1h foreign key (assignment_id) references assignments;
alter table if exists students_assignments add constraint FKblt5trbc9nn3orywwkvrpqwk5 foreign key (student_id) references students;
alter table if exists sub_topics add constraint FKhkg9l1f7q24ab18u0jrmf7u50 foreign key (main_topic_id) references main_topics;
