spring.application.name=alghadeer
server.port=${PORT}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#In prod make ddl false and ddl-auto non
spring.jpa.generate-ddl=${DDL_GENERATION}
spring.jpa.hibernate.ddl-auto=${DDL_STATUS}
spring.flyway.enabled=${FLYWAY_STATUS}

#run this pre FIRST deployment ever to put it in V1
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=src/main/resources/db/migration/V1__init_schema.sql
spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata

server.servlet.session.timeout=${SESSION_TTL}
spring.session.store-type=jdbc
spring.profiles.active=${STAGE}
spring.datasource.hikari.initialization-fail-timeout=${FAIL_TIMEOUT}

file.upload-dir=${FILE_PATH}
image.width=${IMAGE_WIDTH}
image.height=${IMAGE_HEIGHT}
logging.file.name=${LOGGING_FILE}
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level --- [%X{appName}] [%X{cid},%X{thread}] %logger{60} : %msg%n


spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
spring.mail.properties.mail.smtp.starttls.required=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED}
spring.mail.properties.mail.smtp.connectiontimeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT}
spring.mail.properties.mail.smtp.timeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT}
spring.mail.properties.mail.smtp.writetimeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT}

