spring.application.name=alghadeer
server.port=${PORT}
spring.profiles.active=${STAGE}
frontend.origin=${FRONTEND_ORIGIN}
spring.config.import=\
  classpath:properties/database.properties,\
  classpath:properties/mail.properties,\
  classpath:properties/open-api.properties,\
  classpath:properties/logging.properties,\
  classpath:properties/session.properties,\
  classpath:properties/image-upload.properties